#!/bin/bash
# If remontoire is running, kill it.  Otherwise start it.
# Taken from https://github.com/regolith-linux/regolith-ftue/blob/master/remontoire-toggle

remontoire_PID=$(pidof remontoire)

if [ -z "$remontoire_PID" ]
then
    /usr/bin/remontoire -s $(printenv I3SOCK) -t ~/.i3/remontoire.css &
else
    kill $remontoire_PID
fi
